image: registry.gitlab.com/zurnaz/serverless-gitlab-ci-example

stages:
  - build
  - test
  - deploy
  - e2e tests
  - release

variables:
  dev: 'dev-$CI_COMMIT_REF_SLUG'
  CYPRESS_CACHE_FOLDER:  ${CI_PROJECT_DIR}/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - cache/Cypress

install:
  stage: build
  image: cypress/base:10.15.3
  script:
    - yarn install --frozen-lockfile --production

lint:
  stage: test
  image: cypress/base:10.15.3
  script:
    - yarn install --frozen-lockfile
    - yarn lint

unit tests:
  stage: test
  image: cypress/base:10.15.3
  script:
    - yarn install --frozen-lockfile
    - yarn unit

scan dependencies:
  stage: test
  image: fhunii/retire.js
  script:
    - cd ${CI_PROJECT_DIR}
    - yarn install --frozen-lockfile --production
    - retire --path ${CI_PROJECT_DIR} --ignore cache

SAST:
  stage: test
  image: python:3.7-stretch
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install nodejsscan
    - nodejsscan -d ${CI_PROJECT_DIR}/src -o ${CI_PROJECT_DIR}/nodejsscan-results.json
  artifacts:
    untracked: false
    paths:
      - results.json
    expire_in: 4 days

dev:
  stage: deploy
  script:
    - sls deploy -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    on_stop: stop_dev
  artifacts:
    untracked: false
    paths:
      - stack.json
    expire_in: 4 days

e2e tests dev:
  image: cypress/base:10.15.3
  stage: e2e tests
  script:
    - yarn install --frozen-lockfile
    - yarn verify
    - yarn e2e
  only:
    - branches
  except:
    - master
  dependencies:
    - dev

staging:
  stage: deploy
  script:
    - sls deploy -s staging -v
  environment:
    name: staging
    on_stop: stop_staging
  only:
    - master
  artifacts:
    untracked: false
    paths:
      - stack.json

e2e tests staging:
  image: cypress/base:10.15.3
  stage: e2e tests
  script:
    - yarn install --frozen-lockfile
    - yarn e2e
  only:
    - master
  dependencies:
    - staging

deploy live:
  stage: release
  script:
    - sls deploy -s live -v
  environment:
    name: live
  only:
    - master
  when: manual

stop_dev:
  stage: deploy
  script:
    - sls remove -s dev-${CI_COMMIT_REF_SLUG} -v
  only:
    - branches
  except:
    - master
  environment:
    name: dev
    action: stop
  when: delayed
  start_in: 24 hour

stop_staging:
  stage: deploy
  script:
    - sls remove -s staging -v
  environment:
    name: staging
    action: stop
  when: manual
